# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5592dfdce1105a1a48a9d4ed408d9eb379254e59e2b51cba627061c009f0bf6ff632f60eb15759e874b58a734046d1c1e4d6e5cb5268192c181bd75dce45f85e

test:
  secret_key_base: 39001661ea248588a3176d1745a7256abd9139a922e5a012bf72dae7f92f09a9947ef79d11474a4b8c5f855f537b337aa72feba9d00d4f95c27d58ca99846c60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
